# ATTENTION!! DEPRECATED!!!!!!
co = 'color'; op = 'o'; pos = 'pos'
from bgl import *
from gpu_extras.presets import *
from gpu_extras.batch import batch_for_shader as batch
from . gpu_sh import ShaderType as SType,Shader2D,Shader3D,SH,ShaderGeom as SGeom
from . gl_fun import *
def DiLNCommon(_co,s,g): BindSetSingleFloat(s,co,_co); DrawBlend(NewPrimilineBat(s,g),s)
def DiLNsList(_co,_p,p=[], s = Shader2D.UNIFORM()):
    for idx in range(0, len(_p) - 1): p.append(_p[idx]); p.append(_p[idx+1])
    p.append(_p[0]); DiLNCommon(_co,s,{pos:p})
def DiLN(_co,_a,_b): s = Shader2D.UNIFORM(); DiLNCommon(_co,s,{pos:(_a,_b)})
def DiLNs(_co,*_p): s = Shader2D.UNIFORM(); DiLNCommon(_co,s,{pos:list(_p)})
def DiMARCRCTRNDLNsList(_p,_s,_co,_r = 8): DiLNsList(_co,SGeom.R3(_p,_s,_r).get(pos))
def DiMARCRCTRNDLNs(_p,_s,_co,_r = 8, s = Shader2D.UNIFORM()): DiLNCommon(_co,s,SGeom.MARCOR3(_p,_s,_r))
def DiMARCRCT(_p,_s,_co, s = Shader2D.UNIFORM()): DiLNCommon(_co,s,SGeom.MARCOR1(_p,_s))
def DiRCTCommon(_co,s,g,i): BindSetSingleFloat(s,co,_co); DrawBlend(NewGeoBat(s,g,i),s)
def DiRCT(_p,_s,_co, s = Shader2D.UNIFORM()): DiRCTCommon(_co,s,SGeom.R(_p,_s),SGeom.R_IDXS())
def DiRCTCENT(_p,_s,_co, s = Shader2D.UNIFORM()): DiRCTCommon(_co,s,SGeom._R_CENT(_p,_s),SGeom.R_IDXS())
def DiRCTRND(_p,_s,_co,_r = 8, s = Shader2D.UNIFORM()): DiRCTCommon(_co,s,SGeom.R3(_p,_s,_r),SGeom.R3_IDXS())
def DiRCTRNDTOP(_p,_s,_co,_r = 8, s = Shader2D.UNIFORM()): DiRCTCommon(_co,s,SGeom.R3TOP(_p,_s,_r),SGeom.R3TOP_IDXS())
def DiRCTRNDBOT(_p,_s,_co,_r = 8, s = Shader2D.UNIFORM()): DiRCTCommon(_co,s,SGeom.R3BOT(_p,_s,_r),SGeom.R3BOT_IDXS())
def DiIMGACommon(i,s,g): DrawBlend(NewImBat(i,s,g),s)
def DiIMGA(_p,_s,_i, s = SH.IMGA()): DiIMGACommon(_i,s,SGeom.IMG(_p,_s))
def DiIMGAMMA(_p,_s,_i, s = SH.IMGA_GAMMA()): DiIMGACommon(_i,s,SGeom.IMG(_p,_s))
def DiIMGAMMA_OP(_p,_s,_o,_i, s = SH.IMGA_GAMMA_OP()): BindSetSingleFloat(s,op,_o); DiIMGACommon(_i,s,SGeom.IMG(_p,_s))
def DiCL(_c, _r, _seg, _co):draw_circle_2d(_c, _co, _r, _seg)
def DiCLS(_c, _r, _seg, _lt, _co):SetLineSBlend(_lt);DiCL(_c,_r,_seg,_co);RstLineSBlend()
def DiIMG(_p,_s,_i, s = Shader2D.IMAGE()): Draw(NewImBat(_i,s,SGeom.IMG(_p,_s)),s)
def DiCROMA(_c,_r,s):DrawBlendDot(_r,NewDotBat(_c,s),s)#DrawBlendDotSRGB(_c,_r,s)
def DiRCROMA(_c,_r,_h,s=SH.RCROMA_SL()):BindSetSingleFloat(s,'h',_h);DiCROMA(_c,_r,s)
def DiCCROMA(_c,_r,_v,s=SH.CCROMA_HS()):BindSetSingleFloat(s,'v',_v);DiCROMA(_c,_r,s)
def DiCRCROMA(_c,_r,_s,_v,s=SH.CRCROMA_H()):Bind(s);SetFloats(s,**{'s':_s,'v':_v});DiCROMA(_c,_r,s)
def DiRCROMALIN(_c,_r,_h,s=SH.RCROMA_SL_LIN()):BindSetSingleFloat(s,'h',_h);DiCROMA(_c,_r,s)
def DiRCROMANOLIN(_c,_r,_h,s=SH.RCROMA_SL_NOLIN()):BindSetSingleFloat(s,'h',_h);DiCROMA(_c,_r,s)
def DiRCROMALINSLICE(_c,_r,_h,_s,s=SH.RCROMA_SL_LIN_SLICE()):Bind(s);SetFloats(s,**{'h':_h,'xi':_s.min.x,'xf':_s.max.x,'yi':_s.max.y,'yf':_s.min.y});DiCROMA(_c,_r,s)
def DiCFS(_c, _r, _co, s=SH.CFS()):BindSetSingleFloat(s,'co',_co);DrawBlendDot(_r,NewDotBat(_c,s),s)
def DiCFSs(_r, _co, _cs):s=SH.CFS();BindSetSingleFloat(s,'co',_co);DrawBlendDot(_r,batch(s,SType.POINTS(),{"p":_cs}),s)
def DiCFCLS(_c, _r, _co, _lco):DiCFS(_c,_r,_co);DiCLS(_c,_r,32,2,_lco)
def DiBARCromaR(_c,_r,_co,_f=1,s=SH.BARCROMA_R()):Bind(s);SetFloats(s,**{'f':_f,'co':_co});DrawBlendDot(_r,NewDotBat(_c,s),s)
def DiBARCromaH(_c,_r,_s,_v,_f=1,s=SH.BARCROMA_H()):Bind(s);SetFloats(s,**{'f':_f,'s':_s,'v':_v});DrawBlendDot(_r,NewDotBat(_c,s),s)
def DiBARCromaG(_c,_r,_co,_f=1,s=SH.BARCROMA_G()):Bind(s);SetFloats(s,**{'f':_f,'co':_co});DrawBlendDot(_r,NewDotBat(_c,s),s)
def DiBARCromaS(_c,_r,_h,_v,_f=1,s=SH.BARCROMA_S()):Bind(s);SetFloats(s,**{'f':_f,'h':_h,'v':_v});DrawBlendDot(_r,NewDotBat(_c,s),s)
def DiBARCromaB(_c,_r,_co,_f=1,s=SH.BARCROMA_B()):Bind(s);SetFloats(s,**{'f':_f,'co':_co});DrawBlendDot(_r,NewDotBat(_c,s),s)
def DiBARCromaV(_c,_r,_h,_s,_f=1,s=SH.BARCROMA_V()):Bind(s);SetFloats(s,**{'f':_f,'h':_h,'s':_s});DrawBlendDot(_r,NewDotBat(_c,s),s)
def DiRCTGRADLIN(_c,_r,_c1,_c2,_dir,s=SH.RCTGRAD_LIN()):Bind(s);SetV4s(s,**{'co1':_c1,'co2':_c2,'dir':_dir});DiCROMA(_c,_r,s)
def DiRCTGRADNOLIN(_c,_r,_c1,_c2,_dir,s=SH.RCTGRAD_NOLIN()):Bind(s);SetV4s(s,**{'co1':_c1,'co2':_c2,'dir':_dir});DiCROMA(_c,_r,s)
def DiRCTGRADBARLIN(_c,_r,_c1,_c2,_c3,_f,s=SH.RCTGRADBAR_LIN()):Bind(s);SetV4s(s,**{'f':_f,'co1':_c1,'co2':_c2,'co3':_c3});DiCROMA(_c,_r,s)
def DiRCTGRADBARNOLIN(_c,_r,_c1,_c2,_f,s=SH.RCTGRADBAR_NOLIN()):Bind(s);SetV4s(s,**{'f':_f,'co1':_c1,'co2':_c2});DiCROMA(_c,_r,s)
def DiRCTDOTMASK(_c,_r,_co,_s,s=SH.RCTDOT_MASK()):Bind(s);SetFloats(s,**{'co':_co,'xi':_s.min.x,'xf':_s.max.x,'yi':_s.max.y,'yf':_s.min.y});DiCROMA(_c,_r,s)