# ALERT! DEPRECATED!
from bgl import *
from blf import *
from gpu_extras.batch import batch_for_shader as bat
from . gpu_sh import ShaderType as SType, ShaderGeom as SGeom
def SetPoint(ps):glPointSize(ps)
def RstPoint():glPointSize(4.0)
def SetPointBlend(ps):glPointSize(ps);SetBlend()
def RstPointBlend():glPointSize(4.0);RstBlend()
def SetLineSBlend(lt):SetBlend();glEnable(GL_LINE_SMOOTH);glLineWidth(lt)
def RstLineSBlend():RstBlend();glDisable(GL_LINE_SMOOTH);glLineWidth(1.0)
def SetSRGB():glEnable(GL_FRAMEBUFFER_SRGB)
def SetBFuncAlphaZero():glEnable(GL_BLEND);glBlendFunc(GL_SRC_ALPHA,GL_ZERO);glBlendEquation(GL_FUNC_ADD)
def SetBFuncOneAlpha():glEnable(GL_BLEND);glBlendFunc(GL_ONE,GL_ONE_MINUS_SRC_ALPHA);glBlendEquation(GL_FUNC_ADD)
def SetBFuncAlphaAlpha():glEnable(GL_BLEND);glBlendFunc(GL_SRC_ALPHA,GL_ONE_MINUS_SRC_ALPHA);glBlendEquation(GL_FUNC_ADD)
def SetDefCoSpace():glEnable(GL_FRAMEBUFFER_DEFAULT)
def RstColorSpace():glDisable(GL_FRAMEBUFFER_SRGB)
def SetBlend():glEnable(GL_BLEND)
def RstBlend():glDisable(GL_BLEND)
def SetBlendAlpha():SetBlend();glBlendFunc(GL_ONE,GL_ONE_MINUS_SRC_ALPHA)
def SetDepth():glEnable(GL_DEPTH_TEST)
def RstDepth():glDisable(GL_DEPTH_TEST)
def GenBuffer(w,h):return Buffer(GL_BYTE, w*h*4)
def GetPixel(x,y):b=GenBuffer(1,1);glReadPixels(int(x),int(y),1,1,GL_RGBA,GL_UNSIGNED_BYTE,b);return b
def SetFontColor(id,co=(1,1,1,1)):color(id,*co)
def GetFontDim(id,_txt)->tuple:return dimensions(id,_txt)
def SetFontShadow(id,off_x=-1,off_y=-2,lvl=3,co=(0,0,0,1)):enable(id,SHADOW);shadow(id,lvl,*co);shadow_offset(id,off_x,off_y)
def RstFontShadow(id):disable(id,SHADOW)
def SetFontWW(id,width):enable(id,WORD_WRAP);word_wrap(id,width)
def RstFontWW(id):disable(id,WORD_WRAP)
def SetFontClip(id,xi,xf,yi,yf):enable(id,CLIPPING);clipping(id,xi,xf,yi,yf)
def RstFontCLip(id):disable(id,CLIPPING)
def SetClipPosSize(xi,xf,yi,yf):glEnable(GL_SCISSOR_TEST);glScissor(int(xi),int(xf),int(yi),int(yf))
def RstClip():glDisable(GL_SCISSOR_TEST)
def SetFontRot(id,a):enable(id,ROTATION);rotation(id,a)
def RstFontRot(id):disable(id,ROTATION)
def SetFontSize(id,_size,_dpi):size(id,_size,_dpi)
def SetFontSizeGetDim(id,_size,_dpi,_txt)->tuple:SetFontSize(id,_size,_dpi);return GetFontDim(id,_txt)
def DrawBlend(b, s):SetBlend();b.draw(s);RstBlend()
def Draw(b, s):b.draw(s)
def Bind(s):s.bind()
def SetFloat(s,a,b):s.uniform_float(a, b)
def SetFloats(sh,**kwargs):
    for a,b in kwargs.items():
        SetFloat(sh, a, b)
def SetV4(s,a,b):s.uniform_float(a, b)
def SetV4s(sh,**kwargs):
    for a,b in kwargs.items():
        SetV4(sh, a, b)
def BindSetSingleFloat(s,a,b):Bind(s);SetFloat(s, a, b)
def NewGeoBat(s,g,i):return bat(s,SType.TRIS(),g,indices=i)
def NewImBat(i,s,g):BindTex(i); return bat(s,SType.TRIFAN(),g)
def NewPrimilineBat(s,g):return bat(s,SType.LINES(),g)
def NewDotBat(c,s):return bat(s,SType.POINTS(),SGeom.CIR(c))
def DrawBlendDot(r,b,s):SetPointBlend(r*2);Draw(b,s);RstPointBlend()
def BindTex(i): glActiveTexture(GL_TEXTURE0); glBindTexture(GL_TEXTURE_2D,i)
def DrawTxt(id,_x,_y,_txt):position(id,_x,_y,0);draw(id,_txt)
def DrawSRGB(b,s):SetSRGB();Draw(b,s);RstColorSpace()
def DrawBlendDotSRGB(_c,_r,s):SetPointBlend(_r*2);DrawSRGB(NewDotBat(_c,s),s);RstPointBlend()